bdsm_django/urls.py
from __future__ import unicode_literals
from django.conf.urls import url, include
from django.contrib import admin
import django_app.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(django_app.urls)),
]

django_app/urls.py
from __future__ import unicode_literals
from django.conf.urls import url
from django.views.generic import TemplateView
import views

app_name = 'django_app'
urlpatterns = [
    url(r'change_password$', views.change_password,
        name='change_password'),
    url(r'all_ready_not_returned_orders$', views.all_ready_not_returned_orders,
        name='all_ready_not_returned_orders'),
    url(r'create_user$', views.create_user,
        name='create_user'),
    url(r'create_client$', views.create_client,
        name='create_client'),
    url(r'create_bonus$', views.create_bonus,
        name='create_bonus'),
    url(r'create_discount$', views.create_discount,
        name='create_discount'),
    url(r'create_service$', views.create_service,
        name='create_service'),
    url(r'update_service/([0-9]+)$', views.update_service,
        name='update_service'),
    url(r'get_bonuses$', views.get_bonuses,
        name='get_bonuses'),
    url(r'update_bonus/([0-9]+)$', views.update_bonus,
        name='update_bonus'),
    url(r'get_discounts$', views.get_discounts,
        name='get_discounts'),
    url(r'update_discount/([0-9]+)$', views.update_discount,
        name='update_discount'),
    url(r'create_office$', views.create_office,
        name='create_office'),
    url(r'update_office/([0-9]+)$', views.update_office,
        name='update_office'),

    # url(r'edit_order/([0-9]+)$', views.edit_order,
    #     name='edit_order'),
    url(r'return_order/([0-9]+)$', views.return_order,
        name='return_order'),
    url(r'set_order_ready_status/([0-9]+)$', views.set_order_ready_status,
        name='set_order_ready_status'),
    url(r'update_client/([0-9]+)$', views.update_client,
        name='update_client'),
    url(r'clients$', views.get_clients,
        name='clients'),
    url(r'offices$', views.get_offices,
        name='offices'),
    url(r'order/([0-9]+)$', views.get_order_info,
        name='order'),
    url(r'check_order$', views.check_order,
        name='check_order'),
    url(r'client_orders/([0-9]+)$', views.client_orders,
        name='client_orders'),
    url(r'check_client_order$', views.check_client_orders,
        name='check_client_orders'),
    url(r'client_orders_ready_not_returned/([0-9]+)$', views.client_orders_ready_not_returned,
        name='ready_not_returned_orders'),
    url(r'check_order_ready_not_returned$', views.check_client_orders_ready_not_returned,
        name='check_client_orders_ready_not_returned'),
    url(r'client_info/([0-9]+)$', views.client_info,
        name='client_info'),
    url(r'check_client_info$', views.check_client_info,
        name='check_client_info'),
    url(r'logout$', views.logout,
        name='logout'),
    url(r'login$', views.login,
        name='login'),
    url(r'register$', views.register,
        name='register'),
    url(r'services$', views.services,
        name='services'),
    url(r'add_order$', views.order,
        name='add_order'),
    url(r'all_orders$', views.all_orders,
        name='all_orders'),
    url(r'$', TemplateView.as_view(template_name='django_app/index.html'),
        name='index'),
]

django_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

django_app/views.py
from __future__ import print_function, unicode_literals
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages
from django.core.urlresolvers import reverse
from list_requests import list_request
from .forms import \
(
    OrderIdForm,
    ClientIdForm,
    LoginForm,
    RegistrationForm,
    OrderForm,
    OrderFormToValidate,
    ClientForm,
    ChangePasswordForm,
    CreateUserForm,
    BonusForm,
    DiscountForm,
    ServiceForm,
    OfficeForm
)
from .db_functions import \
(
    login as logging_in,
    register as register_in_db,
    insert_order,
    mark_order_returned as set_order_status_to_returned,
    set_order_ready,
    update_client as update_client_in_db,
    update_user_password,
    create_user_in_db,
    create_bonus_in_db,\
    call_procedure_in_db,
    call_function_in_db
)

from errors import AccessDeniedError, ACCESS_DENIED_MESSAGE
from utils import to_index_page, convert_to_type


def catch_access_denied(foo):
    def inner(*args, **kwargs):
        try:
            return foo(*args, **kwargs)
        except AccessDeniedError as e:
            messages.error(args[0], ACCESS_DENIED_MESSAGE)
            return to_index_page()
    return inner


@catch_access_denied
def change_password(request):
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            if update_user_password(request, request.COOKIES['username'], form.cleaned_data['password_1']):
                messages.info(request, 'Password changed successfully')
                return to_index_page()
    else:
        form = ChangePasswordForm()
    return render(request, 'django_app/update_pass_form.html', {'form': form})


@catch_access_denied
def get_clients(request):
    row_names, data = list_request(request, 'get_clients')
    return render(request, 'django_app/client_list.html',
                  {"headers": row_names, "data": data,
                   'extra_thing': {'url': 'django_app:update_client',
                                   'text': 'Update client'}})


@catch_access_denied
def update_client(request, client_id):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            if update_client_in_db(request,
                                   form.cleaned_data['first_name'],
                                   form.cleaned_data['last_name'],
                                   client_id):
                messages.info(request, 'Client updated successfully')
            else:
                messages.error(request, 'Error while updating')
            return to_index_page()
    else:
        row_names, record = list_request(request, 'client_info', [int(client_id)])
        client_id, first_name, last_name, best_client = record[0]
        form = ClientForm(data={'first_name': first_name, 'last_name': last_name, 'best_client': best_client})
    return render(request, 'django_app/client_form.html', {'form': form, 'id': client_id})


@catch_access_denied
def client_info(request, client_id):
    row_names, data = list_request(request, 'client_info', [int(client_id)])
    is_ready_index = row_names.index('Best client')
    data = convert_to_type(data, bool, is_ready_index)

    return render(request, 'django_app/client_info.html',
                  {"headers": row_names, "data": data,
                   'extra_thing': {'url': 'django_app:update_client', 'text': 'Update client'}
                   })


@catch_access_denied
def get_offices(request):
    row_names, data = list_request(request, 'get_offices')
    extra_thing = None
    if 'connection' in request.COOKIES and request.COOKIES['connection'] == 'admin':
        extra_thing = {'url': 'django_app:update_office', 'text': 'Update office'}
    return render(request, 'django_app/list_template.html',
                  {"headers": row_names, "data": data, 'extra_thing': extra_thing})



@catch_access_denied
def update_office(request, office_id):
    if request.method == 'POST':
        form = OfficeForm(request.POST)
        if form.is_valid():
            if call_procedure_in_db(request, 'update_office_by_id',
                                    [int(office_id),
                                     form.cleaned_data['location'],
                                     form.cleaned_data['description']]):
                messages.info(request, 'Office updated!')
            else:
                messages.error(request, 'Error while updating')
            return to_index_page()
    else:
        row_names, record = list_request(request, 'get_office_by_id', [int(office_id)])
        _, loc, description = record[0]
        form = OfficeForm(data={'location': loc, 'description': description})
    return render(request, 'django_app/edit_form_template.html', {'form': form, 'id': office_id,
                                                                  'url_': 'django_app:update_office'})


@catch_access_denied
def get_order_info(request, order_id):
    row_names, data = list_request(request, 'get_order_info', [int(order_id)])
    is_ready_index = row_names.index('Is ready')

    data = convert_to_type(data, bool, is_ready_index)
    return render(request, 'django_app/order_status.html',
                  {"headers": row_names, "data": data})


@catch_access_denied
def check_order(request):
    if request.method == 'POST':
        form = OrderIdForm(request.POST)
        if form.is_valid():
            return HttpResponseRedirect(reverse('django_app:order', args=(form.cleaned_data['order_id'],)))
    else:
        form = OrderIdForm()
    return render(request, 'django_app/check_order.html', {"form": form})


@catch_access_denied
def client_orders(request, client_id):
    row_names, data = list_request(request, 'client_orders', [int(client_id)])
    is_ready_index = row_names.index('Is ready')
    data = convert_to_type(data, bool, is_ready_index)

    return render(request, 'django_app/client_orders_list.html',
                  {"headers": row_names, "data": data})


@catch_access_denied
def check_client_orders(request):
    if request.method == 'POST':
        form = ClientIdForm(request.POST)
        if form.is_valid():
            return HttpResponseRedirect(reverse('django_app:client_orders',
                                                args=(form.cleaned_data['client_id'],)))
    else:
        form = ClientIdForm()
    return render(request, 'django_app/check_client_orders.html', {"form": form})


@catch_access_denied
def all_ready_not_returned_orders(request):
    row_names, data = list_request(request, 'get_ready_not_returned_orders')
    is_ready_index = row_names.index('Is ready')
    data = convert_to_type(data, bool, is_ready_index)

    extra_thing = None
    if 'connection' in request.COOKIES and request.COOKIES['connection'] == 'worker':
        extra_thing = {'url': 'django_app:return_order', 'text': 'Return'}
    return render(request, 'django_app/orders_ready_not_returned_list.html',
                  {"headers": row_names, "data": data, 'extra_thing': extra_thing})


@catch_access_denied
def client_orders_ready_not_returned(request, client_id):
    row_names, data = list_request(request, 'ready_not_returned', [int(client_id)])
    is_ready_index = row_names.index('Is ready')
    data = convert_to_type(data, bool, is_ready_index)

    extra_thing = None
    if 'connection' in request.COOKIES and request.COOKIES['connection'] == 'worker':
        extra_thing = {'url': 'django_app:return_order', 'text': 'Return'}
    return render(request, 'django_app/orders_ready_not_returned_list.html',
                  {"headers": row_names, "data": data, 'extra_thing': extra_thing})


@catch_access_denied
def check_client_orders_ready_not_returned(request):
    if request.method == 'POST':
        form = ClientIdForm(request.POST)
        if form.is_valid():
            return HttpResponseRedirect(reverse('django_app:ready_not_returned_orders',
                                                args=(form.cleaned_data['client_id'],)))
    else:
        form = ClientIdForm()
    return render(request, 'django_app/check_orders_ready_not_returned.html', {"form": form})


@catch_access_denied
def check_client_info(request):
    if request.method == 'POST':
        form = ClientIdForm(request.POST)
        if form.is_valid():
            return HttpResponseRedirect(reverse('django_app:client_info',
                                                args=(form.cleaned_data['client_id'],)))
    else:
        form = ClientIdForm()
    return render(request, 'django_app/check_client_info.html', {"form": form})


@catch_access_denied
def logout(request):
    resp = to_index_page()
    resp.delete_cookie('username')
    resp.delete_cookie('connection')
    resp.delete_cookie('client_id')
    return resp


@catch_access_denied
def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            login_successful, cookie_values = logging_in(form.cleaned_data['login'],
                                                         form.cleaned_data['password'])
            if login_successful:
                messages.info(request, 'Login successful')
                resp = to_index_page()
                resp.set_cookie('username', cookie_values['username'])
                resp.set_cookie('connection', cookie_values['connection'])
                resp.set_cookie('client_id', cookie_values['client_id'])
                return resp
            messages.error(request,  'Login failed')
        else:
            messages.error(request, 'Invalid form')
        return render(request, 'django_app/login_form.html', {"form": form})
    else:
        form = LoginForm()
    return render(request, 'django_app/login_form.html', {"form": form})


@catch_access_denied
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)

django_app/templates/django_app/bonus_form.html
{% extends 'django_app/base_template.html' %}
{% block title %}Create user{% endblock %}
{% block content %}

<form action="{% url 'django_app:create_bonus' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="Create">
</form>

{% endblock %}

django_app/templates/django_app/client_form.html
{% extends 'django_app/base_template.html' %}
{% block title %}Client updating{% endblock %}
{% block content %}

<form action="{% url 'django_app:update_client' id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="send">
</form>

{% endblock %}

django_app/templates/django_app/client_info.html
{% extends 'django_app/list_template.html' %}
{% block title %}Client{% endblock %}
{% block header %}Client information{% endblock %}
{% block not_found %}No client{% endblock %}

django_app/templates/django_app/client_orders_list.html
{% extends "django_app/list_template.html" %}
{% block title %}ClientList{% endblock %}
{% block header %}Order of client{% endblock %}
{% block not_found %}No orders{% endblock %}

django_app/templates/django_app/create_user_form.html
{% extends 'django_app/base_template.html' %}
{% block title %}Create user{% endblock %}
{% block content %}

<form action="{% url 'django_app:create_user' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="Create">
</form>

{% endblock %}

django_app/templates/django_app/edit_form_template.html
{% extends 'django_app/base_template.html' %}
{% block title %}Create user{% endblock %}
{% block content %}

    {% if message %}
        <h3 class="header">{{ message }}</h3>
    {% endif %}
<form action="{% url url_ id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="Create">
</form>

{% endblock %}

django_app/templates/django_app/form_template.html
{% extends 'django_app/base_template.html' %}
{% block title %}Create user{% endblock %}
{% block content %}

    {% if message %}
        <h3 class="header">{{ message }}</h3>
    {% endif %}
<form action="{% url url_ %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="Create">
</form>

{% endblock %}

django_app/templates/django_app/list_template.html
{% extends "django_app/base_template.html" %}
{% block title %}{% endblock %}
{% block content %}
{% if error %}
    <h2 class="header">Access denied, peachy!</h2>
{% else %}
    {% if data %}
        <h2 class="header">{% block header %}{% endblock %}</h2>
        <table class="table table-bordered">
            <thead>
                <tr>
                    {% for header_name in headers %}
                        <td style="font-weight: bold">{{ header_name }}</td>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>

            {% for record in data %}
                <tr>
                {% for record_value in record %}
                    <td>{{ record_value }}</td>
                {% endfor %}
                {% if extra_thing %}
                    <td><a href="{% url extra_thing.url record.0 %}">{{ extra_thing.text}}</a></td>
                {% endif %}
                </tr>
            {% endfor %}
            </tbody>

        </table>
    {% else %}
       <h2 class="header">{% block not_found %}{% endblock %}</h2>
    {% endif %}
{% endif %}
{% endblock %}

django_app/templates/django_app/login_form.html
{% extends 'django_app/base_template.html' %}
{% block title %}Login{% endblock %}

{% block content %}
    {% if message %}
        <h2 class="header">{{ message }}</h2>
    {% endif %}
    <form action="{% url 'django_app:login' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn" value="Login" type="submit">
    </form>

{% endblock %}

django_app/templates/django_app/offices_list.html
{% extends "django_app/list_template.html" %}
{% block title %}Offices list{% endblock %}
{% block header %}All offices{% endblock %}
{% block not_found %}No offices found{% endblock %}

django_app/templates/django_app/orders_list.html
{% extends "django_app/base_template.html" %}
{% block title %}Orders list{% endblock %}
{% block content %}
{% if error %}
    <h2 class="header">Access denied, peach!</h2>
{% else %}
    {% if data %}
        <h2 class="header">{% block header %}{% endblock %}</h2>
        <table class="table table-bordered">
            <thead>
                <tr>
                    {% for header_name in headers %}
                        <td style="font-weight: bold">{{ header_name }}</td>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>

            {% for record in data %}
                <tr>
                {% for record_value in record %}
                    <td>{{ record_value }}</td>
                {% endfor %}
{#                <td><a href="{% url 'django_app:edit_order' record.0 %}">Edit</a></td>#}
                <td><a href="{% url 'django_app:set_order_ready_status' record.0  %}">Set ready</a></td>
                <td><a href="{% url 'django_app:return_order' record.0  %}">Return order</a></td>

                </tr>
            {% endfor %}
            </tbody>

        </table>
    {% else %}
       <h2 class="header">{% block not_found %}{% endblock %}</h2>
    {% endif %}
{% endif %}
{% endblock %}

django_app/templates/django_app/orders_ready_not_returned_list.html
{% extends "django_app/list_template.html" %}
{% block title %}Ready orders{% endblock %}
{% block header %}Ready{% endblock %}
{% block not_found %}No such orders{% endblock %}

django_app/templates/django_app/service_types_list.html
{% extends 'django_app/list_template.html' %}
{% block title %}Services{% endblock %}
{% block header %}Services available{% endblock %}
{% block  not_found %}No services found{% endblock %}

django_app/templates/django_app/update_pass_form.html
{% extends 'django_app/base_template.html' %}
{% block title %}Client updating{% endblock %}
{% block content %}
    {% if message %}
        <h2 class="header">{{ message }}</h2>
    {%  endif %}
<form action="{% url 'django_app:change_password' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="send">
</form>

{% endblock %}